site_name: Template API Docs

docs_dir: docs

nav:
  - Home: docs/README.md
  - API Reference:
      - OpenAPI: docs/openapi.md

theme:
  name: material

plugins:
  - search
  - openapi_markdown:
      enabled: true
      openapi_file: docs/openapi.json
      output_file: docs/openapi.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true