site_name: Template API Docs
site_url: https://teplotax.github.io/doc-api-template-v1/

nav:
  - Home: README.md
  - API Reference:
      - OpenAPI: openapi.md

theme:
  name: material

plugins:
  - search
  - openapi_markdown:
      enabled: true
      openapi_file: openapi.json
      output_file: openapi.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true