site_name: Template API Docs

nav:
  - Home: README.md
  - API Reference:
      - OpenAPI: openapi.json

theme:
  name: material

plugins:
  - search
  - openapi

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true